export const UPDATE_TOPLIST ='UPDATE_TOPLIST';
export const UPDATE_MUSUCLIST ='UPDATE_MUSICLIST';
export const UPDATE_MOVIELIST ='UPDATE_MOVIELIST';
export const UPDATE_SCIENCELIST ='UPDATE_SCIENCELIST';
export const UPDATE_NEWLIST ='UPDATE_NEWLIST';
export const UPDATE_HOTLIST ='UPDATE_HOTLIST';

export const UPDATE_USER ='UPDATE_USER';
export const UPDATE_MSGBOX ='UPDATE_MSGBOX';

export const UPDATE_NAV = 'UPDATE_NAV';

export const UPDATE_LOADING = 'UPDATE_LOADING';
