// export const UPDATE_TOPLIST ='UPDATE_TOPLIST';
// export const UPDATE_MUSUCLIST ='UPDATE_MUSICLIST';
// export const UPDATE_MOVIELIST ='UPDATE_MOVIELIST';
// export const UPDATE_SCIENCELIST ='UPDATE_SCIENCELIST';
// export const UPDATE_NEWLIST ='UPDATE_NEWLIST';
// export const UPDATE_HOTLIST ='UPDATE_HOTLIST';
//这部分数据适合集中管理，
 export const UPDATE_LIST ='UPDATE_LIST';

export const UPDATE_USER ='UPDATE_USER';
export const UPDATE_MSGBOX ='UPDATE_MSGBOX';

export const UPDATE_WNAV = 'UPDATE_WNAV';
export const UPDATE_WTOP = 'UPDATE_WTOP';
export const UPDATE_WLOADING = 'UPDATE_WLOADING';
